# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{sinefunc-rstakeout}
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["edvardw", "topfunky"]
  s.date = %q{2010-05-03}
  s.default_executable = %q{rstakeout}
  s.description = %q{This gem watches a given directory for any changes and executes a given command when something is changed.}
  s.email = %q{rico@sinefunc.com}
  s.executables = ["rstakeout"]
  s.extra_rdoc_files = [
    "README.md"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "README.md",
     "Rakefile",
     "VERSION",
     "bin/rstakeout",
     "data/images/fail.png",
     "data/images/ok.png"
  ]
  s.homepage = %q{http://github.com/sinefunc/rstakeout}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{Watches a directory for any changes}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

